[project]
name = "modelops-calabaria"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "modelops-bundle",
    "modelops-contracts",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
modelops-contracts = { path = "../modelops-contracts" }
modelops-bundle = { path = "../modelops-bundle" }
